- hosts: localhost
  connection: local
  vars:

  # scripts needs to placed in service-config-changes/files
    configuration_scripts_to_run:
      - configure_hbase.py
      - configure_yarn.py


  roles:
     - role: cm-api-libs
     - role: get-hue-db-password
#     - role: install-kafka
#     - role: enable-hdfs-ha
     - role: service-config-changes
